{
  "formatVersion": "1.1",
  "component": {
    "group": "org.yuyan",
    "module": "command-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "command-utils-0.0.1.jar",
          "url": "command-utils-0.0.1.jar",
          "size": 9695,
          "sha512": "b471cb53edd70d79e2de9f7a09d814e705c228f835466959de7e425fc55bc0faffb3fd5539fe1105ce31ee30e8a1940eade04d9769ababfdc34c94ebcd627de1",
          "sha256": "1188aaecfc5973a90a661f4615ddabb6e68526074c230691c2b6d891446da29b",
          "sha1": "74077a13142f0b455fc2538dc8fb4c0f58529556",
          "md5": "7bc6a1e9e653a1c8917d4cc4d5c1493c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "command-utils-0.0.1.jar",
          "url": "command-utils-0.0.1.jar",
          "size": 9695,
          "sha512": "b471cb53edd70d79e2de9f7a09d814e705c228f835466959de7e425fc55bc0faffb3fd5539fe1105ce31ee30e8a1940eade04d9769ababfdc34c94ebcd627de1",
          "sha256": "1188aaecfc5973a90a661f4615ddabb6e68526074c230691c2b6d891446da29b",
          "sha1": "74077a13142f0b455fc2538dc8fb4c0f58529556",
          "md5": "7bc6a1e9e653a1c8917d4cc4d5c1493c"
        }
      ]
    }
  ]
}
