{
  "formatVersion": "1.1",
  "component": {
    "group": "org.yuyan",
    "module": "command-utils",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "command-utils-0.0.1.jar",
          "url": "command-utils-0.0.1.jar",
          "size": 9698,
          "sha512": "8c57b414cd25c18430db56e473ff7e9adb0e6b4de6acf78db15c31a6692171b319b36e387acdcb7cb27736c6741982721fb6e4b36e7e2662926cb18cfba1b20d",
          "sha256": "c4a1cf3dcaeeae65eabe5b8881b2c163c0f10d3a83736c7f4baafdb480ae9c17",
          "sha1": "a176a873558092088974a9008a81073155880434",
          "md5": "ff0de38942181ad1265ca02a94f9c27b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "command-utils-0.0.1.jar",
          "url": "command-utils-0.0.1.jar",
          "size": 9698,
          "sha512": "8c57b414cd25c18430db56e473ff7e9adb0e6b4de6acf78db15c31a6692171b319b36e387acdcb7cb27736c6741982721fb6e4b36e7e2662926cb18cfba1b20d",
          "sha256": "c4a1cf3dcaeeae65eabe5b8881b2c163c0f10d3a83736c7f4baafdb480ae9c17",
          "sha1": "a176a873558092088974a9008a81073155880434",
          "md5": "ff0de38942181ad1265ca02a94f9c27b"
        }
      ]
    }
  ]
}
